#! /bin/sh

if [ "$SPKG_LOCAL" = "" ]; then
   echo "SPKG_LOCAL undefined ... exiting";
   echo "Maybe run 'qsnake --shell'?"
   exit 1
fi


set -e

unset RM
CPPFLAGS="-I$SPKG_LOCAL/include" ./configure --prefix="$SPKG_LOCAL"
make
make install
